/*
 * @(#)BrowserTest.java  1.0  13 February 2005
 *
 * Copyright (c) 2004 Werner Randelshofer
 * Staldenmattweg 2, Immensee, CH-6405, Switzerland.
 * All rights reserved.
 *
 * The copyright of this software is owned by Werner Randelshofer. 
 * You may not use, copy or modify this software, except in  
 * accordance with the license agreement you entered into with  
 * Werner Randelshofer. For details see accompanying license terms. 
 */

package test;

import ch.randelshofer.quaqua.DefaultBrowserCellRenderer;

/**
 * BrowserTest.
 *
 * @author  Werner Randelshofer
 * @version 1.0  13 February 2005  Created.
 */
public class BrowserTest extends javax.swing.JPanel {
    
    /** Creates new form. */
    public BrowserTest() {
        initComponents();
        
        browser2.setCellRenderer(new DefaultBrowserCellRenderer());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new javax.swing.JScrollPane();
        browser1 = new ch.randelshofer.quaqua.JBrowser();
        scrollPane2 = new javax.swing.JScrollPane();
        browser2 = new ch.randelshofer.quaqua.JBrowser();

        setLayout(new java.awt.GridLayout(0, 1));

        scrollPane1.setViewportView(browser1);

        add(scrollPane1);

        scrollPane2.setViewportView(browser2);

        add(scrollPane2);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ch.randelshofer.quaqua.JBrowser browser1;
    private ch.randelshofer.quaqua.JBrowser browser2;
    private javax.swing.JScrollPane scrollPane1;
    private javax.swing.JScrollPane scrollPane2;
    // End of variables declaration//GEN-END:variables
    
}
