/*
 * @(#)NativeTest.java  1.0  2009-06-09
 * 
 * Copyright (c) 2009 Werner Randelshofer
 * Staldenmattweg 2, Immensee, CH-6405, Switzerland.
 * All rights reserved.
 * 
 * The copyright of this software is owned by Werner Randelshofer. 
 * You may not use, copy or modify this software, except in  
 * accordance with the license agreement you entered into with  
 * Werner Randelshofer. For details see accompanying license terms.
 */

package test;

/**
 * NativeTest.
 *
 * @author Werner Randelshofer
 * @version 1.0 2009-06-09 Created.
 */
public class NativeTest extends javax.swing.JPanel {

    /** Creates new form NativeTest */
    public NativeTest() {
        initComponents();
        tabbedPane.add(new LazyPanel("test.FileSystemTest"), "File System");
        tabbedPane.add(new LazyPanel("test.ClipboardTest"), "Clipboard");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());
        add(tabbedPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

}
