/*
 * @(#)QuaquaTest.java  1.0  2009-09-12
 * 
 * Copyright (c) 2009 Werner Randelshofer
 * Staldenmattweg 2, Immensee, CH-6405, Switzerland.
 * All rights reserved.
 * 
 * The copyright of this software is owned by Werner Randelshofer. 
 * You may not use, copy or modify this software, except in  
 * accordance with the license agreement you entered into with  
 * Werner Randelshofer. For details see accompanying license terms.
 */
package test;

import ch.randelshofer.quaqua.QuaquaManager;
import javax.swing.*;

/**
 * QuaquaTest.-
 *
 * @author Werner Randelshofer
 * @version 1.0 2009-09-12 Created.
 */
public class QuaquaTest extends javax.swing.JFrame {

    /** Creates new form QuaquaTest */
    public QuaquaTest() {
       // getRootPane().putClientProperty("apple.awt.brushMetalLook", Boolean.TRUE);
        ((JComponent) getContentPane()).setOpaque(true);
        add(new LazyPanel("test.QuaquaExplorer"));
        initComponents();
        setSize(700, 600);
        setTitle(UIManager.getLookAndFeel().getName() + " " +
                QuaquaManager.getVersion() +
                " on Java " + System.getProperty("java.version")+" "+System.getProperty("os.arch"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        UIManager.setLookAndFeel("ch.randelshofer.quaqua.QuaquaLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new QuaquaTest().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
