/*
 * TransparentJFrameTest14.java
 *
 * Created on 24. Februar 2007, 16:19
 */

package test;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author  werni
 */
public class TransparentJFrameTest14 extends javax.swing.JFrame {
    
    /**
     * Creates new form TransparentJFrameTest14
     */
    public TransparentJFrameTest14() {
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        getRootPane().putClientProperty(
                "apple.awt.draggableWindowBackground", Boolean.FALSE
                );
        setLayout(new FlowLayout());
        
        setBackground(new Color(0x80000000,true));
        //((JComponent) getContentPane()).setOpaque(true);
        //((JComponent) getContentPane()).setBackground(Color.LIGHT_GRAY);
        
        JPanel p = new JPanel() {
            public void paintComponent(Graphics gr) {
                super.paintComponents(gr);
                Graphics2D g = (Graphics2D) gr;
                g.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC));
                g.setColor(new Color(0,true));
                g.fillOval(0,0,getWidth(),getHeight());
            }
        };
        p.setPreferredSize(new Dimension(60,60));
        getContentPane().add(p);
        setSize(300,300);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        getContentPane().setLayout(new java.awt.FlowLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransparentJFrameTest14().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
