/*
 * BoxTest14.java
 *
 * Created on January 4, 2007, 8:28 PM
 */

package test;

import javax.swing.*;
import javax.swing.border.*;
/**
 *
 * @author  werni
 */
public class BoxTest14 extends javax.swing.JPanel {
    
    /**
     * Creates new form BoxTest14
     */
    public BoxTest14() {
        initComponents();
        
        Box box = new Box(BoxLayout.Y_AXIS);
        box.setBorder(new TitledBorder("Ångström"));
        box.add(new JButton("Ångström"));
        add(box);
    }
    
    public static void main(String[] args) {
        
        JFrame f = new JFrame("Box Test");
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.getContentPane().add(new BoxTest14());
        f.pack();
        f.show();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
