/*
 * @(#)MatisseRadioButtonsTest.java  1.0  September 17, 2006
 *
 * Copyright (c) 2006 Werner Randelshofer
 * Staldenmattweg 2, CH-6405 Immensee, Switzerland
 * All rights reserved.
 *
 * The copyright of this software is owned by Werner Randelshofer. 
 * You may not use, copy or modify this software, except in  
 * accordance with the license agreement you entered into with  
 * Werner Randelshofer. For details see accompanying license terms. 
 */

package test;

import ch.randelshofer.quaqua.*;
import javax.swing.*;
/**
 * MatisseRadioButtonsTest.
 *
 * @author Werner Randelshofer
 * @version 1.0 September 17, 2006 Created.
 */
public class MatisseRadioButtonsTest extends javax.swing.JPanel {
    
    /** Creates a new form. */
    public MatisseRadioButtonsTest() {
        initComponents();
    }

    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(QuaquaManager.getLookAndFeelClassName());
            UIManager.put("Quaqua.Debug.showClipBounds", true);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        JFrame f = new JFrame("GroupLayout Bad Example");
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        MatisseRadioButtonsTest nt = new MatisseRadioButtonsTest();
        f.getContentPane().add(nt);
        f.pack();
        f.setVisible(true);
        //nt.test();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup = new javax.swing.ButtonGroup();
        label1 = new javax.swing.JLabel();
        radioButton1 = new javax.swing.JRadioButton();
        radioButton2 = new javax.swing.JRadioButton();
        radioButton3 = new javax.swing.JRadioButton();

        label1.setText("Radio Buttons Label");

        buttonGroup.add(radioButton1);
        radioButton1.setSelected(true);
        radioButton1.setText("Radio Button 1");

        buttonGroup.add(radioButton2);
        radioButton2.setText("Radio Button 2");

        buttonGroup.add(radioButton3);
        radioButton3.setText("Radio Button 3");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(label1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(radioButton1)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .add(radioButton2)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .add(radioButton3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(label1)
                    .add(radioButton1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(radioButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(radioButton3)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel label1;
    private javax.swing.JRadioButton radioButton1;
    private javax.swing.JRadioButton radioButton2;
    private javax.swing.JRadioButton radioButton3;
    // End of variables declaration//GEN-END:variables
    
}
