/*
 * @(#)OSXPainterTest.java  1.0  2011-07-26
 * 
 * Copyright (c) 2011 Werner Randelshofer, Immensee, Switzerland.
 * All rights reserved.
 * 
 * You may not use, copy or modify this file, except in compliance with the
 * license agreement you entered into with Werner Randelshofer.
 * For details see accompanying license terms.
 */
package test;

import ch.randelshofer.quaqua.osx.OSXAquaPainter;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferInt;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 * OSXPainterTest.
 *
 * @author Werner Randelshofer
 * @version 1.0 2011-07-26 Created.
 */
public class OSXPainterTest extends javax.swing.JPanel {

    private static class Canvas extends JPanel {

        private BufferedImage image;

        private OSXAquaPainter painter;

        public Canvas() {
            System.out.println("OSXPainterTest nativeCodeAvailable="+OSXAquaPainter.isNativeCodeAvailable());
painter=new OSXAquaPainter();
painter.setWidget(OSXAquaPainter.Widget.buttonPush);
        }
        
        
        
        @Override
        public void paintComponent(Graphics gr) {
            int w = getWidth(), h = getHeight();
            if (image == null || image.getWidth() != w || image.getHeight() != h) {
                image = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB_PRE);
            }
            
            int[] data=((DataBufferInt)image.getRaster().getDataBuffer()).getData();
            //painter.paint(data, image.getWidth(), image.getHeight(), 0, 0, 40, 40);
            painter.paint(image, 0, 0, 40, 40);
         
            
            gr.drawImage(image, 0, 0, this);
        }
    }
    
    private Canvas canvas;

    /** Creates new form OSXPainterTest */
    public OSXPainterTest() {
        initComponents();
        add(canvas=new Canvas());
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
        public void run() {
            JFrame f =new JFrame("OSXPainterTest");
            f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            f.add(new OSXPainterTest());
            f.setSize(400,400);
            f.setVisible(true);
        }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
