/*
 * @(#)ToolBarTest.java  1.0  13 February 2005
 *
 * Copyright (c) 2004 Werner Randelshofer
 * Staldenmattweg 2, Immensee, CH-6405, Switzerland.
 * All rights reserved.
 *
 * The copyright of this software is owned by Werner Randelshofer. 
 * You may not use, copy or modify this software, except in  
 * accordance with the license agreement you entered into with  
 * Werner Randelshofer. For details see accompanying license terms. 
 */

package test;

import java.awt.event.*;
import javax.swing.*;
/**
 * ToolBarTest.
 *
 * @author  Werner Randelshofer
 * @version 1.0  13 February 2005  Created.
 */
public class ToolBarTest extends javax.swing.JPanel {
    
    /** Creates new form. */
    public ToolBarTest() {
        initComponents();
        toolBar1.addSeparator();
        toolBar1.add(new AbstractAction("Action") {
            public void actionPerformed(ActionEvent evt) {
                
            }
        });
        toolBar2.addSeparator();
        toolBar2.putClientProperty("JToolBar.isRollover",Boolean.TRUE);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        toolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        toolBar2 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jComboBox2 = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("jLabel1");
        jLabel1.setAlignmentX(0.5F);
        toolBar1.add(jLabel1);

        jButton1.setText("jButton1");
        jButton1.setAlignmentX(0.5F);
        toolBar1.add(jButton1);

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.setAlignmentX(0.5F);
        toolBar1.add(jToggleButton1);

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.setAlignmentX(0.5F);
        toolBar1.add(jCheckBox1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "jComboBox" }));
        toolBar1.add(jComboBox1);

        add(toolBar1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        toolBar2.setName("ToolBar with Title");
        jLabel2.setText("jLabel1");
        jLabel2.setAlignmentX(0.5F);
        toolBar2.add(jLabel2);

        jButton2.setText("jButton1");
        jButton2.setAlignmentX(0.5F);
        toolBar2.add(jButton2);

        jToggleButton2.setText("jToggleButton1");
        jToggleButton2.setAlignmentX(0.5F);
        toolBar2.add(jToggleButton2);

        jCheckBox2.setText("jCheckBox1");
        jCheckBox2.setAlignmentX(0.5F);
        toolBar2.add(jCheckBox2);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "jComboBox" }));
        toolBar2.add(jComboBox2);

        jPanel1.add(toolBar2, java.awt.BorderLayout.NORTH);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToolBar toolBar1;
    private javax.swing.JToolBar toolBar2;
    // End of variables declaration//GEN-END:variables
    
}
