/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_randelshofer_quaqua_osx_OSXSheetSupport */

#ifndef _Included_ch_randelshofer_quaqua_osx_OSXSheetSupport
#define _Included_ch_randelshofer_quaqua_osx_OSXSheetSupport
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: isNativeCodeAvailable */
#undef ch_randelshofer_quaqua_osx_OSXSheetSupport_EXPECTED_NATIVE_CODE_VERSION
#define ch_randelshofer_quaqua_osx_OSXSheetSupport_EXPECTED_NATIVE_CODE_VERSION 0L
/* Inaccessible static: lastID */
/* Inaccessible static: listeners */
/* Inaccessible static: htmlPattern */
/* Inaccessible static: class_00024ch_00024randelshofer_00024quaqua_00024osx_00024OSXSheetSupport */
/*
 * Class:     ch_randelshofer_quaqua_osx_OSXSheetSupport
 * Method:    nativeGetNativeCodeVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_osx_OSXSheetSupport_nativeGetNativeCodeVersion
  (JNIEnv *, jclass);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXSheetSupport
 * Method:    nativeShowOptionSheet
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;Ljava/lang/String;Ljava/awt/Component;I)V
 */
JNIEXPORT void JNICALL Java_ch_randelshofer_quaqua_osx_OSXSheetSupport_nativeShowOptionSheet
  (JNIEnv *, jclass, jstring, jobjectArray, jstring, jboolean, jobjectArray, jstring, jobject, jint);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXSheetSupport
 * Method:    createNativeView
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_ch_randelshofer_quaqua_osx_OSXSheetSupport_createNativeView
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXSheetSupport
 * Method:    nativeHideSheet
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_randelshofer_quaqua_osx_OSXSheetSupport_nativeHideSheet
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXSheetSupport
 * Method:    nativeSetBounds
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_ch_randelshofer_quaqua_osx_OSXSheetSupport_nativeSetBounds
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXSheetSupport
 * Method:    showSheet
 * Signature: (Ljava/awt/Window;J)V
 */
JNIEXPORT void JNICALL Java_ch_randelshofer_quaqua_osx_OSXSheetSupport_showSheet
  (JNIEnv *, jclass, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
