/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_randelshofer_quaqua_osx_OSXSheetSupport */

#ifndef _Included_ch_randelshofer_quaqua_osx_OSXSheetSupport
#define _Included_ch_randelshofer_quaqua_osx_OSXSheetSupport
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: isNativeCodeAvailable */
#undef ch_randelshofer_quaqua_osx_OSXSheetSupport_EXPECTED_NATIVE_CODE_VERSION
#define ch_randelshofer_quaqua_osx_OSXSheetSupport_EXPECTED_NATIVE_CODE_VERSION 0L
/* Inaccessible static: lastID */
/* Inaccessible static: listeners */
/* Inaccessible static: htmlPattern */
/* Inaccessible static: class_00024ch_00024randelshofer_00024quaqua_00024osx_00024OSXSheetSupport */
/*
 * Class:     ch_randelshofer_quaqua_osx_OSXSheetSupport
 * Method:    nativeGetNativeCodeVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_osx_OSXSheetSupport_nativeGetNativeCodeVersion
  (JNIEnv *, jclass);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXSheetSupport
 * Method:    nativeShowOptionSheet
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;Ljava/lang/String;Ljava/awt/Component;I)V
 */
JNIEXPORT void JNICALL Java_ch_randelshofer_quaqua_osx_OSXSheetSupport_nativeShowOptionSheet
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jboolean, jobjectArray, jstring, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
