/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_randelshofer_quaqua_filechooser_Files */

#ifndef _Included_ch_randelshofer_quaqua_filechooser_Files
#define _Included_ch_randelshofer_quaqua_filechooser_Files
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_randelshofer_quaqua_filechooser_Files_FILE_TYPE_ALIAS
#define ch_randelshofer_quaqua_filechooser_Files_FILE_TYPE_ALIAS 2L
#undef ch_randelshofer_quaqua_filechooser_Files_FILE_TYPE_DIRECTORY
#define ch_randelshofer_quaqua_filechooser_Files_FILE_TYPE_DIRECTORY 1L
#undef ch_randelshofer_quaqua_filechooser_Files_FILE_TYPE_FILE
#define ch_randelshofer_quaqua_filechooser_Files_FILE_TYPE_FILE 0L
#undef ch_randelshofer_quaqua_filechooser_Files_FILE_TYPE_UNKOWN
#define ch_randelshofer_quaqua_filechooser_Files_FILE_TYPE_UNKOWN -1L
#undef ch_randelshofer_quaqua_filechooser_Files_EXPECTED_NATIVE_CODE_VERSION
#define ch_randelshofer_quaqua_filechooser_Files_EXPECTED_NATIVE_CODE_VERSION 4L
/* Inaccessible static: labelColors */
/* Inaccessible static: isNativeCodeAvailable */
/* Inaccessible static: class_00024ch_00024randelshofer_00024quaqua_00024filechooser_00024Files */
/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    nativeGetFileType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_nativeGetFileType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    nativeResolveAlias
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_nativeResolveAlias__Ljava_lang_String_2Z
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    nativeResolveAliasType
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_nativeResolveAliasType__Ljava_lang_String_2Z
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    nativeToSerializedAlias
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_nativeToSerializedAlias
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    nativeResolveAlias
 * Signature: ([BZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_nativeResolveAlias___3BZ
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    nativeResolveAliasType
 * Signature: ([BZ)I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_nativeResolveAliasType___3BZ
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    nativeGetLabel
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_nativeGetLabel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    nativeGetKindString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_nativeGetKindString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    nativeGetIconImage
 * Signature: (Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_nativeGetIconImage
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    nativeGetBasicItemInfoFlags
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_nativeGetBasicItemInfoFlags
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    nativeGetDisplayName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_nativeGetDisplayName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    nativeGetImageFromFile
 * Signature: (Ljava/lang/String;II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_nativeGetImageFromFile
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    nativeGetNativeCodeVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_nativeGetNativeCodeVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
