/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_randelshofer_quaqua_filechooser_Files */

#ifndef _Included_ch_randelshofer_quaqua_filechooser_Files
#define _Included_ch_randelshofer_quaqua_filechooser_Files
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_randelshofer_quaqua_filechooser_Files_FILE_TYPE_ALIAS
#define ch_randelshofer_quaqua_filechooser_Files_FILE_TYPE_ALIAS 2L
#undef ch_randelshofer_quaqua_filechooser_Files_FILE_TYPE_DIRECTORY
#define ch_randelshofer_quaqua_filechooser_Files_FILE_TYPE_DIRECTORY 1L
#undef ch_randelshofer_quaqua_filechooser_Files_FILE_TYPE_FILE
#define ch_randelshofer_quaqua_filechooser_Files_FILE_TYPE_FILE 0L
#undef ch_randelshofer_quaqua_filechooser_Files_FILE_TYPE_UNKOWN
#define ch_randelshofer_quaqua_filechooser_Files_FILE_TYPE_UNKOWN -1L
#undef ch_randelshofer_quaqua_filechooser_Files_EXPECTED_NATIVE_CODE_VERSION
#define ch_randelshofer_quaqua_filechooser_Files_EXPECTED_NATIVE_CODE_VERSION 2L
/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    getFileType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_getFileType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    resolveAlias
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_resolveAlias
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    resolveAliasType
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_resolveAliasType
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    toSerializedAlias
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_toSerializedAlias
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    jniResolveAlias
 * Signature: ([BZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_jniResolveAlias
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    jniResolveAliasType
 * Signature: ([BZ)I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_jniResolveAliasType
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    getLabel
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_getLabel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    getKindString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_getKindString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    getIconImage
 * Signature: (Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_getIconImage
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    getBasicItemInfoFlags
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_getBasicItemInfoFlags
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    getDisplayName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_getDisplayName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    nativeGetImageFromFile
 * Signature: (Ljava/lang/String;II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_nativeGetImageFromFile
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     ch_randelshofer_quaqua_filechooser_Files
 * Method:    getNativeCodeVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_filechooser_Files_getNativeCodeVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
