/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_randelshofer_quaqua_app_Application */

#ifndef _Included_ch_randelshofer_quaqua_app_Application
#define _Included_ch_randelshofer_quaqua_app_Application
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_randelshofer_quaqua_app_Application_DEBUG
#define ch_randelshofer_quaqua_app_Application_DEBUG 1L
/* Inaccessible static: isNativeCodeAvailable */
#undef ch_randelshofer_quaqua_app_Application_EXPECTED_NATIVE_CODE_VERSION
#define ch_randelshofer_quaqua_app_Application_EXPECTED_NATIVE_CODE_VERSION 2L
/* Inaccessible static: class_00024ch_00024randelshofer_00024quaqua_00024app_00024Application */
/* Inaccessible static: class_00024ch_00024randelshofer_00024quaqua_00024QuaquaIconFactory */
/*
 * Class:     ch_randelshofer_quaqua_app_Application
 * Method:    nativeRequestUserAttention
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ch_randelshofer_quaqua_app_Application_nativeRequestUserAttention
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     ch_randelshofer_quaqua_app_Application
 * Method:    nativeGetIconImage
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ch_randelshofer_quaqua_app_Application_nativeGetIconImage
  (JNIEnv *, jclass, jint);

/*
 * Class:     ch_randelshofer_quaqua_app_Application
 * Method:    nativeGetNativeCodeVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_app_Application_nativeGetNativeCodeVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
