/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_randelshofer_quaqua_osx_OSXAquaPainter_WindowType */

#ifndef _Included_ch_randelshofer_quaqua_osx_OSXAquaPainter_WindowType
#define _Included_ch_randelshofer_quaqua_osx_OSXAquaPainter_WindowType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
