/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_randelshofer_quaqua_datatransfer_NSPasteboardTransferable */

#ifndef _Included_ch_randelshofer_quaqua_datatransfer_NSPasteboardTransferable
#define _Included_ch_randelshofer_quaqua_datatransfer_NSPasteboardTransferable
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: isNativeCodeAvailable */
/* Inaccessible static: EXPECTED_NATIVE_CODE_VERSION */
/* Inaccessible static: class_00024ch_00024randelshofer_00024quaqua_00024datatransfer_00024NSPasteboardTransferable */
/*
 * Class:     ch_randelshofer_quaqua_datatransfer_NSPasteboardTransferable
 * Method:    nativeGetTypes
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ch_randelshofer_quaqua_datatransfer_NSPasteboardTransferable_nativeGetTypes
  (JNIEnv *, jclass);

/*
 * Class:     ch_randelshofer_quaqua_datatransfer_NSPasteboardTransferable
 * Method:    nativeGetDataForType
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ch_randelshofer_quaqua_datatransfer_NSPasteboardTransferable_nativeGetDataForType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_datatransfer_NSPasteboardTransferable
 * Method:    nativeGetNativeCodeVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_datatransfer_NSPasteboardTransferable_nativeGetNativeCodeVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
