/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_randelshofer_quaqua_osx_Application */

#ifndef _Included_ch_randelshofer_quaqua_osx_Application
#define _Included_ch_randelshofer_quaqua_osx_Application
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_randelshofer_quaqua_osx_Application_DEBUG
#define ch_randelshofer_quaqua_osx_Application_DEBUG 1L
#undef ch_randelshofer_quaqua_osx_Application_EXPECTED_NATIVE_CODE_VERSION
#define ch_randelshofer_quaqua_osx_Application_EXPECTED_NATIVE_CODE_VERSION 1L
/*
 * Class:     ch_randelshofer_quaqua_osx_Application
 * Method:    jniRequestUserAttention
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ch_randelshofer_quaqua_osx_Application_jniRequestUserAttention
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     ch_randelshofer_quaqua_osx_Application
 * Method:    jniGetIconImage
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ch_randelshofer_quaqua_osx_Application_jniGetIconImage
  (JNIEnv *, jclass, jint);

/*
 * Class:     ch_randelshofer_quaqua_osx_Application
 * Method:    getNativeCodeVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_osx_Application_getNativeCodeVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
